name: Build and deploy Python project to Azure Function App - CryptoGetData

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Root path of your function app
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies into Azure Functions compatible structure
        run: |
          mkdir -p CryptoGetData/.python_packages/lib/site-packages
          pip install -r requirements.txt --target="./CryptoGetData/.python_packages/lib/site-packages"

      - name: Prepare artifact for deployment
        run: |
          mkdir package
          cp host.json requirements.txt package/
          cp -r CryptoGetData package/CryptoGetData
          cd package
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F3B01A932B4421C9C493B6531D4CEA8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C3E386A65DAF4521864E947E2D9F3C7D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A7B5AD3A665B464DB561F5FF4F598033 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'CryptoGetData'
          slot-name: 'Production'
          package: .
